In [76]:
import pandas as pd
import numpy as np

In [ ]:
test_file = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"

df = pd.read_csv(test_file)

In [31]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   engine_displacement  9704 non-null   int64
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64
 6   origin               9704 non-null   object
 7   fuel_type            9704 non-null   object
 8   drivetrain           9704 non-null   object
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB

In [107]:
df['fuel_type'].unique().size

2

In [136]:
pd.isna(df).any().value_counts()

False    7
True     4
Name: count, dtype: int64

In [96]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [ ]:
print(df['horsepower'].median())
print(df['horsepower'].mode())
horsepower = df['horsepower'].fillna(df['horsepower'].mode())
print(horsepower.median())

149.0
0    152.0
Name: horsepower, dtype: float64
149.0

In [ ]:
X = df[['vehicle_weight', 'model_year']].head(7)
XT = X.transpose()
XTX = np.matmul(XT, X)
XTX

                vehicle_weight    model_year
vehicle_weight    6.470773e+07  4.247135e+07
model_year        4.247135e+07  2.826475e+07

In [99]:
INV = np.linalg.inv(XTX)
INV

array([[ 1.12464107e-06, -1.68991495e-06],
       [-1.68991495e-06,  2.57468996e-06]])

In [100]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [101]:
w = np.matmul(INV, XT).dot(y)
w

0    0.070997
1    0.419313
dtype: float64

In [102]:
w.sum()

np.float64(0.4903094879707425)